name: ArtenityAuth
version: '0.0.1-SNAPSHOT'
main: org.artenity.auth.Main
api-version: '1.21'
commands:
  login:
    description: Login command
  register:
    description: Register command
  captcha:
    description: Captcha challenge